### ISSUE TITLE
Blocks sometimes do not render

### ISSUE THREAD

**Issue by Eddie02345** [Doregon/PojavOptimize#7]
![Screenshot_20210502-141257_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/74363581/116804407-0f295600-ab51-11eb-8a89-b08f6500f897.jpg)
@bghyt @Doregon

**Comment by zeyrox1090** [comment]
No one will fix this

**Comment by bghyt** [comment]
You need to turn off chuck face culling and compact vertex format in the settings.

> ![Screenshot_20210502-141257_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/74363581/116804407-0f295600-ab51-11eb-8a89-b08f6500f897.jpg)
> @bghyt @Doregon
